### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined at IncomingMessage.Readable.unpipe

### ISSUE THREAD

**Issue by ganesansays** [cplee/lambda-express#1]
First of all, a great idea to. Thanks for this.

How ever I get this error while trying to use this ... 

TypeError: Cannot read property 'pipesCount' of undefined at IncomingMessage.Readable.unpipe (_stream_readable.js:652:12) at unpipe (/var/task/node_modules/express/node_modules/finalhandler/node_modules/unpipe/index.js:47:12) at send (/var/task/node_modules/express/node_modules/finalhandler/index.js:146:3) at Object.<anonymous> (/var/task/node_modules/express/node_modules/finalhandler/index.js:107:5) at Object.<anonymous> (/var/task/node_modules/express/lib/router/index.js:618:15) at Object.immediate._onImmediate (timers.js:381:16) at processImmediate [as _immediateCallback](timers.js:363:15)

Appreciate your help.

**Comment by cplee** [comment]
@ganesansays what version of express are you using?

**Comment by ganesansays** [comment]
@cplee, sorry couldnt respond. Have moved away for this for a while. Will post when I get back to this.

**Comment by cdock1029** [comment]
I'm also seeing this

`"express": "^4.14.0"`
