### ISSUE TITLE
Work with Binary data?

### ISSUE THREAD

**Issue by JoshLaseter** [cplee/lambda-express#2]
Have you gotten this working with binary data? I'm trying to return a PDF and am having issues. I think it's on the API-Gateway side based on posts on the AWS forums (e.g. https://forums.aws.amazon.com/thread.jspa?threadID=219124) but thought I'd check if you've gotten it working. Setting heading mapping as you specified got it returning as a PDF, but didn't actually load (corrupted, again as in the linked aws forum thread). 

Thanks!

**Comment by cplee** [comment]
@JoshLaseter Yea, unfortunately binary data is not supported  via API Gateway at this time (see https://forums.aws.amazon.com/thread.jspa?threadID=220351   .... actually I see your name on the thread).

Best solution I've found is put the data in S3, and return a signed URL, and have API Gateway return a Location header with the URL.

**Comment by JoshLaseter** [comment]
Yes, I've been poking around everywhere. I keep seeing the official word is that it's not supported and yet people seem to be tantalizingly close and/or said they got it working without explaining how. Thanks for the reply and the module! I'll just have to keep an autoscaling EC2 until such time as binary data is supported, but this will definitely be helpful for migrating once that happens.
